[package]
name = "gta-berlin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
[dependencies]
berlin-engine = { path = "../engine" }
berlin-map-loader = { path = "../map_loader" }
anyhow.workspace = true
berlin-sim = { path = "../sim" }
berlin-audio = { path = "../audio" }
glam.workspace = true
serde_json.workspace = true
